!#/bin/bash

# Install projectmill
mkdir lib
cd lib
git clone https://github.com/mapbox/projectmill.git

# Setup symlinks
TILEMILL_PROJECTS_BASE=$TRANSIT_MAPS_BASE/Tilemill
GTFS_TILEMILL=gtfs_sf
ln -s $TILEMILL_PROJECTS_BASE/$GTFS_TILEMILL $MAPBOX_PROJECTS/$GTFS_TILEMILL
GTFS_TILEMILL=gtfs_seattle
ln -s $TILEMILL_PROJECTS_BASE/$GTFS_TILEMILL $MAPBOX_PROJECTS/$GTFS_TILEMILL
GTFS_TILEMILL=gtfs_corvallis
ln -s $TILEMILL_PROJECTS_BASE/$GTFS_TILEMILL $MAPBOX_PROJECTS/$GTFS_TILEMILL